runtime bundle/vim-pathogen/autoload/pathogen.vim

call pathogen#infect()

runtime! plugin/matchit.vim
runtime! plugin/tmux_navigator.vim

set autoindent
set nobackup
set colorcolumn=80
set nocompatible
set expandtab
set hidden
set nohlsearch
set incsearch
set laststatus=2
set relativenumber
set ruler
set softtabstop=2
set shiftwidth=2
set spell spelllang=en_us
set noswapfile
set tabstop=2
set wildmode=longest,list
set nowrap

filetype plugin indent on
filetype indent on
syntax enable

let mapleader=","

map <silent> <Up> gk
map <silent> <Down> gj
map <silent> <Left> h
map <silent> <Right> l
map <silent> <home> g<home>
map <silent> <End> g<End>

noremap <Esc>h :vertical resize -5<cr>
noremap <Esc>j :resize +5<cr>
noremap <Esc>k :resize -5<cr>
noremap <Esc>l :vertical resize +5<cr>

noremap te :tabe<cr>
noremap th :tabp<cr>
noremap tH :tabfirst<cr>
noremap tl :tabn<cr>
noremap tL :tablast<cr>

map <f5> :w \| :call system("tmux resize -t1 -y20 && tmux send -t1 !! c-j")<cr>
imap <f5> <esc> <f5>
map <f6> :w \| :call system("tmux resize -t0 -Z")<cr>
imap <f6> <esc> <f6>
map <f7> :w \| :call system("tmux resize -t1 -y40")<cr>
imap <f7> <esc> <f7>

map <Leader>h :Tab /=><cr>
map <Leader>H :Tab /:\zs/l1r0<cr>

map <Leader>t :NERDTreeToggle<cr>

autocmd BufNewFile,BufRead COMMIT_EDITMSG set colorcolumn=50,72

autocmd BufNewFile,BufRead *.haml,*.slim set wrap

autocmd BufNewFile,BufRead *.adoc,*.md,*.txt set linebreak
autocmd BufNewFile,BufRead *.adoc,*.md,*.txt set norelativenumber
autocmd BufNewFile,BufRead *.adoc,*.md,*.txt set wrap

autocmd BufNewFile,BufRead Vagrantfile,Procfile,Guardfile,Gemfile,gemspec,*.gemspec set filetype=ruby

let $PATH="./bin:".$PATH

set backspace=2
set t_kb=
set t_kD=[3~
set t_Co=256

set background=light
colorscheme solarized

if filereadable(glob("~/.vimrc.local"))
  source ~/.vimrc.local
endif
