execute pathogen#infect()

set nocompatible
filetype plugin indent on
set t_Co=256
syntax enable
set background=dark
colorscheme detailed
set number
set laststatus=2
filetype indent on
set nohlsearch
set incsearch
set ruler
set autoindent
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set nowrap
set colorcolumn=80
set backup
set backupdir=~/.vim/tmp
set directory=~/.vim/tmp
set wildmode=longest,list
set hidden

let mapleader=","

set backspace=indent,eol,start
set t_kb=
set t_kD=[3~
noremap  <Up> ""
noremap! <Up> <Esc>
noremap  <Down> ""
noremap! <Down> <Esc>
noremap  <Left> ""
noremap! <Left> <Esc>
noremap  <Right> ""
noremap! <Right> <Esc>

nnoremap K i<CR><Esc>

noremap <Esc>H :vertical resize -5<cr>
noremap <Esc>J :resize +5<cr>
noremap <Esc>K :resize -5<cr>
noremap <Esc>L :vertical resize +5<cr>

noremap te :tabe<Space>
noremap th :tabfirst<cr>
noremap tj :tabp<cr>
noremap tk :tabn<cr>
noremap tl :tablast<cr>

map <f5> :w \| :call system("tmux resize -t1 -y20 && tmux send -t1 !! c-j")<cr>
map <f6> :w \| :call system("tmux resize -t0 -Z")<cr>
map <f7> :w \| :call system("tmux resize -t1 -y40")<cr>

map <Leader>h :Tab /=><cr>
map <Leader>H :Tab /:\zs/l1r0<cr>

imap <f5> <esc> <f5>
imap <f6> <esc> <f6>
imap <f7> <esc> <f7>

runtime! macros/matchit.vim
runtime! plugin/tmux_navigator.vim

autocmd BufNewFile,BufRead COMMIT_EDITMSG set colorcolumn=50,72
autocmd BufNewFile,BufRead *.haml set wrap
autocmd BufNewFile,BufRead *.slim set wrap
autocmd BufNewFile,BufRead *.md set wrap

autocmd BufNewFile,BufRead *.slim set syntax=slim

autocmd BufNewFile,BufRead Vagrantfile,Procfile,Guardfile,Gemfile set filetype=ruby

let $PATH="./bin:".$PATH
