set nocompatible
filetype plugin indent on
set t_Co=256
syntax enable
set background=dark
colorscheme railscasts
set number
set laststatus=2
filetype indent on
set nohlsearch
set incsearch
set ruler
set autoindent
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set nowrap
set colorcolumn=80
set backup
set backupdir=~/.vim/tmp
set directory=~/.vim/tmp
set wildmode=longest,list

noremap  <Up> ""
noremap! <Up> <Esc>
noremap  <Down> ""
noremap! <Down> <Esc>
noremap  <Left> ""
noremap! <Left> <Esc>
noremap  <Right> ""
noremap! <Right> <Esc>

nnoremap K i<CR><Esc>

map <C-S-l> :bnext<cr>
map <C-S-h> :bprevious<cr>

map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

runtime! macros/matchit.vim

autocmd BufNewFile,BufRead COMMIT_EDITMSG set colorcolumn=50,72
autocmd BufNewFile,BufRead *.haml set wrap
autocmd BufNewFile,BufRead *.md set wrap
